export const TRADING_PAIRS = [
  {
    symbol: "BTC/USDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    providerSymbol: "BTCUSDT",
    name: "Bitcoin",
    precision: { price: 2, amount: 6 },
    minNotional: 25,
    makerFeeRate: 0.0008,
    takerFeeRate: 0.001,
    featured: true,
  },
  {
    symbol: "ETH/USDT",
    baseAsset: "ETH",
    quoteAsset: "USDT",
    providerSymbol: "ETHUSDT",
    name: "Ethereum",
    precision: { price: 2, amount: 5 },
    minNotional: 20,
    makerFeeRate: 0.0008,
    takerFeeRate: 0.001,
    featured: true,
  },
  {
    symbol: "BNB/USDT",
    baseAsset: "BNB",
    quoteAsset: "USDT",
    providerSymbol: "BNBUSDT",
    name: "BNB",
    precision: { price: 2, amount: 4 },
    minNotional: 15,
    makerFeeRate: 0.0009,
    takerFeeRate: 0.0011,
  },
  {
    symbol: "SOL/USDT",
    baseAsset: "SOL",
    quoteAsset: "USDT",
    providerSymbol: "SOLUSDT",
    name: "Solana",
    precision: { price: 3, amount: 3 },
    minNotional: 10,
    makerFeeRate: 0.0009,
    takerFeeRate: 0.0011,
    featured: true,
  },
  {
    symbol: "ADA/USDT",
    baseAsset: "ADA",
    quoteAsset: "USDT",
    providerSymbol: "ADAUSDT",
    name: "Cardano",
    precision: { price: 4, amount: 1 },
    minNotional: 10,
    makerFeeRate: 0.001,
    takerFeeRate: 0.0012,
  },
  {
    symbol: "XRP/USDT",
    baseAsset: "XRP",
    quoteAsset: "USDT",
    providerSymbol: "XRPUSDT",
    name: "XRP",
    precision: { price: 4, amount: 1 },
    minNotional: 10,
    makerFeeRate: 0.001,
    takerFeeRate: 0.0012,
  },
  {
    symbol: "DOT/USDT",
    baseAsset: "DOT",
    quoteAsset: "USDT",
    providerSymbol: "DOTUSDT",
    name: "Polkadot",
    precision: { price: 3, amount: 2 },
    minNotional: 10,
    makerFeeRate: 0.001,
    takerFeeRate: 0.0012,
  },
];

export const PAIR_BY_SYMBOL = Object.fromEntries(TRADING_PAIRS.map((pair) => [pair.symbol, pair]));

export const DEFAULT_ACCOUNT_ID = "demo-institution";

export const ASSET_RISK_TIERS = {
  BTC: "core",
  ETH: "core",
  USDT: "stable",
  BNB: "large-cap",
  SOL: "growth",
  ADA: "growth",
  XRP: "growth",
  DOT: "growth",
};
